name: CI

on:
  push:
  pull_request:

env:
  php_extensions: 'dom, iconv, intl, json, mbstring, opcache, pcntl, pcov, session, simplexml, xml, zip, xdebug'
  key: cache-v0.1

jobs:
  lint:
    runs-on: '${{ matrix.operating_system }}'
    timeout-minutes: 20
    strategy:
      matrix:
        operating_system: [ubuntu-latest]
        php_versions: ['8.3']
        experimental: [false]
        include:
          - operating_system: 'ubuntu-latest'
            php_versions: '8.4'
            experimental: true
      fail-fast: false
    env:
      PHP_CS_FIXER_FUTURE_MODE: '0'
    name: 'Linter / PHP ${{ matrix.php_versions }}'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup cache environment'
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: '${{ matrix.php_versions }}'
          extensions: '${{ env.php_extensions }}'
          key: '${{ env.key }}'
      - name: 'Cache extensions'
        uses: actions/cache@v1
        with:
          path: '${{ steps.cache-env.outputs.dir }}'
          key: '${{ steps.cache-env.outputs.key }}'
          restore-keys: '${{ steps.cache-env.outputs.key }}'
      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_versions }}
          extensions: '${{ env.php_extensions }}'
          ini-values: memory_limit=-1
          tools: pecl, composer
          coverage: none
      - name: 'Setup problem matchers for PHP (aka PHP error logs)'
        run: 'echo "::add-matcher::${{ runner.tool_cache }}/php.json"'
      - name: 'Setup problem matchers for PHPUnit'
        run: 'echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"'
      - name: 'Install PHP dependencies with Composer'
        continue-on-error: ${{ matrix.experimental }}
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader
        working-directory: './'
      - name: 'Linting PHP source files'
        continue-on-error: ${{ matrix.experimental }}
        run: 'vendor/bin/ecs check --config=ecs.php .'
